### PR TITLE
Hack around not being able to find names for consts

### PR DESCRIPTION
**Pull request by akatrevorjay**
There's no doubt a better way to handle this (I've only barely read through autowrap), but this quick traversal hack has worked for me so far. I'm unsure of the possible effects of doing this.

``` c
const char * http_errno_name(http_errno err);
ctypedef int (*http_data_cb)(http_parser*, const char *at, size_t length);
```

Without this, consts like the above raise an AttributeError as there's no name attribute on the parent object we're trying to retrieve the name of.

### CODE REVIEW

**Comment by hroest** [comment]
seems reasonable to me, I guess this would solve all kinds of issues with `const`, `const ptr`, `const &` and other such constructs, correct? 
Concerning the side effects, it seems that  at least the tests still run but we probably should add tests for `const char * fxn()` or something

**Comment by hroest** [comment]
@uweschmitt what do you think?

**Comment by uweschmitt** [comment]
@hroest this is what I wanted to suggest: to have a few additional tests for declarations involving an additional `const`.

**Comment by uweschmitt** [comment]
@akatrevorjay I overlooked this pull request for some time. Could you add some tests including `const` declarations ?

**Comment by akatrevorjay** [comment]
Hi @uweschmitt , I probably won't have time for a bit, but I can try to squeeze it in this week.

**Comment by uweschmitt** [comment]
Don't hurry. I pity that I overlooked your request.

**Comment by akatrevorjay** [comment]
Happens to the best of us bud, no worries.

**Comment by uweschmitt** [comment]
I failed to merge this without breaking tests. 

@hroest do you have time to have a closer look at this resp. if the changes are still required?

**Comment by timosachsenberg** [comment]
feel free to reopen if still relevant

**Pull request closed without merging**
