### PR TITLE
added: wrapper for '/' operator and tests

### PR DESCRIPTION
**Pull request by satvik-tha-god**
Changed these files:
autowrap/CodeGenerator.py
tests/test_code_generator_minimal.py
tests/test_files/minimal.hpp
tests/test_files/minimal.pxd

Kindly test and review

For issue #129

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Hi,

Python 3.x uses __truediv__ and __floordiv__. __div__ is 2.x-only.

**Comment by satvik-tha-god** [comment]
Kindly check now 

Should work now

**Comment by jpfeuffer** [comment]
Looks good. I was wondering if all those methods could be refactored so that code is reused as much as possible. I see a lot of duplication.
Also, I know our current code style is not very good. It would be cool if we start to have type hints and documentation for every method that we touch.

**Comment by satvik-tha-god** [comment]
I will add all of the important operators first so that I see any potential issues that I face first. 

Then I can maybe work on refactoring the duplicated code

**Pull request merged**
