### PR TITLE
Added: '-=', '*=', '/=' operators

### PR DESCRIPTION
**Pull request by satvik-tha-god**
Changed the following files:
autowrap/CodeGenerator.py
autowrap/data_files/autowrap/autowrap_tools.hpp
tests/test_code_generator_minimal.py
tests/test_files/minimal.hpp
tests/test_files/minimal.pxd

For issue,
#129

### CODE REVIEW

**Comment by jpfeuffer** [comment]
By the way, can you add your changes to the changelog please?

**Comment by satvik-tha-god** [comment]
Where exactly is the changelog? I am sorry I am not familiar with it 

The one in the root directory was edited 2 months ago

**Comment by jpfeuffer** [comment]
yes this.

**Comment by jpfeuffer** [comment]
No, just add your change:

- Added support for missing operators +-/....

**Comment by jpfeuffer** [comment]
Thanks. Looks good. Next step would be to try to refactor some duplication.

**Comment by jpfeuffer** [comment]
Can also be done in a new PR, as discussed.

**Pull request merged**
