### PR TITLE
Add buffer protocol generator and example

### PR DESCRIPTION
**Pull request by mobiusklein**
This is a draft of the modifications needed to add support for automatically generating `__getbuffer__` and `__releasebuffer__` logic so that `autowrap`-wrapped objects can implement the [buffer protocol](https://docs.python.org/3/c-api/buffer.html). This isn't finished (no formal tests yet, though I have tested by hand), but I wanted to get feedback on how the directive should be specified. Right now, it's a triplet separated by commas:
```
        # wrap-buffer-protocol:
        #    <expression on self to get the buffer address>,<buffer type>,<expression on self to get buffer size in items>
        #
```
Filled in from the example:
```
        # wrap-buffer-protocol:
        #    data_.data(),float,size()
        #
```
This doesn't feel clean, requiring complex expressions in two places on a single line and relies on a delimiter that could appear in those expressions, ",". It seems like directives spread over multiple lines are separate instructions, but an object can only export a buffer one way, so I might be able to instead split the above into:
```
        # wrap-buffer-protocol:
        #    data_.data()
        #    float
        #    size()
```
This only supports exporting simple buffers of scalars cleanly and only of a single dimension (no strided matrices).

The manual testing on the example amounts to
```python
import py_vec_holder
import numpy as np

holder = py_vec_holder.VecHolder()
holder.add(1.0)
holder.add(2.0)
holder.add(3.0)

view = np.asarray(holder)
assert np.allclose(view, [1.0, 2.0, 3.0])
assert view.base.obj is holder
```

### CODE REVIEW

**Comment by jpfeuffer** [comment]
Hi! Thanks for the pull request. I don't think the directive format matters much.
If a user wants complex constructs to get to the data, it is probably best to use a custom extension.

I think the only important test missing is a test where this class shows up in a function argument or as a return value (i.e. in the ConversionProviders). However I do not expect troubles.

Can this be combined with already wrapped classes, where the content is stored as a shared_ptr<CObject> inst?

**Comment by jpfeuffer** [comment]
I think strides will be harder, since C++ nested vectors do not store the raw data contiguously. But we can merge in steps.

**Comment by mobiusklein** [comment]
`vector<vector<T>>` isn't a single contiguous buffer or organized in any reliable manner, so this wouldn't apply. Exporting strided buffers is tricky but how often do you need it?

> Can this be combined with already wrapped classes, where the content is stored as a shared_ptr inst?
If I understand your question, you have a class like this:
```cpp
class MyWrapper {
    public:
        shared_ptr<vector<float>> shared_data;
};
```
and you want to wrap it with the buffer protocol, how would you export the buffer for `shared_data`?

The `<expression on self to get the buffer address>` would be `cython.deref(self.inst.shared_data).data()`, access the wrapping shared pointer, dereference `MyWrapper::shared_data` to get the actual `vector<float>` and then call `vector::data` to get the address of the `float*` owned by the `vector` instance. Then, the lifetime of the `autowrap`-generated class that encloses `MyWrapper` would keep alive the `MyWrapper` instance via its shared pointer, and then the `MyWrapper` instance keeps `MyWrapper::shared_data` alive via its shared pointer.

So long as that pointer is not modified via reallocation/mucking about with the `vector<float>`'s internals, then the Python-visible buffer is safe, as in the previous discussion. Violate those guarantees and you're in UB territory.

I'll see if I can track down the test case you mentioned.

**Comment by jpfeuffer** [comment]
Yes strided buffers are not super important right now. I just gave some ideas since you mentioned that they were not supported yet. I will make a feature issue.

Yes that makes sense for objects with shared_ptr inst. Just wanted to double check. It is just that this is the standard way of wrapping C++ classes in autowrap. With a buffer, it would allow a convenient representation of an object with a "main" vector and some additional functionality right?

Cool! If I find time I will add some tests too and play around with this. Yes returning some buffered vector from a larger object would be something interesting to test. I haven't thought it through completely yet.

**Comment by mobiusklein** [comment]
I'm still polishing the syntax (so it doesn't rely on comma delimiter) and trying to figure out how to add tests. Do you want me to keep working on that?

**Comment by jpfeuffer** [comment]
Ah sorry on the phone your examples looked like tests. My idea was to merge quick so that @jcharkow could test it in OpenMS.

**Comment by jpfeuffer** [comment]
Feel free to move the examples to tests.

Under test_code_generstor.py, just add a new function. Copy everything from another function, adapt the pxd paths and module names, write code using the module.
Run pytest.

That should be roughly it

**Comment by jpfeuffer** [comment]
And the syntax is a great first approach. Sure, I am happy to discuss improvements.

**Pull request merged**
